### ISSUE TITLE
EOS Nation Colorado Ambassador

### ISSUE THREAD

**Issue by EOSDenver** [EOS-Nation/Ambassadors#4]
EOS Nation Ambassador Candidate - COLORADO, US

**Brandon Hughes**
USA/CO/Colorado Springs
![fullsizeoutput_a0a](https://user-images.githubusercontent.com/37320115/37321684-0a9932f8-263f-11e8-866d-a6f10e30f04e.jpeg)

WHO? Native Texan but soul anchored in Colorado. I LOVE hockey for all you Canadians out there. I hold fond memories of getting absolutely CRUSHED during my summer hockey tours across Canada. I eventually made it to US Hockey Olympic Development before blowing out my ACL twice. I still have a great love for the game. 

I cranked out a 4.0 GPA through my Junior year at the University of Colorado before dropping out to trade Eurodollar interest rates professionally on the Chicago Mercantile Exchange. I worked 70-90 hours a week, slept under my desk (crawling out only when markets were moving) and traded billions in interest rate futures per month. I witnessed and rode the wave of the first US debt downgrade, and had a front seat to the LIBOR rigging scandal (just watching, not rigging). Ultimately, it was seeing the rise of spoofing, fake paper via algorithmic trading that drove me to follow a different career path. Ever since, I've been in wealth management for the last 6 years overseeing a half billion USD in assets for high-net-worth and ultra-HNW individuals and their families.

Some in my workplace have been dubbed me "the problem child" because of the content I bring to our conversations, from cryptocurrencies to transhumanism. If it were not for my forward thinking company and the fact my boss is a righteous man, I would probably be unemployed long ago. But, I remain, and I am steadily gaining influence and respect due to discussing fringe emerging technologies long before they enter their collective consciousness.

My coworkers have also dubbed me the "Most Interesting Man in the Office" (a scornful spin on the Dos Equis commercials). I've backpacked around the world, fed whitetip/hammerhead sharks scuba diving in Fiji while living with the Chief of a Fijian tribe, jumped out of a helicopter and also participated in an oxygen assisted skydive from 23000 feet. Cycling (both road and mountain) is a balancing influence in my life. Whether climbing to the top of Pikes Peak or attempting the White Rim Road 100MTB ride by moonlight, cycling has kept me on the relative straight and narrow. I am a rated helicopter/fixed wing pilot and have been fortunate enough to drop into some tremendous back country heliboarding across our Colorado mountains. **I go into all of this only to say that I see money merely as a conduit to create indelible experiences with the people you love.** 

If EOS does go to the moon, a key intent for me is to get my hands dirty and help build a better world with all the solutions I have come across in my life. Additionally, I'm looking forward to tackling some AMAZING adventures with a lot of incredible people. Becoming a EOS Nation Ambassador is a step along that path.

PS. I am also the Co-Founder of EOS Denver with Steve Floyd (EOS Dallas). He has been invaluable in helping me build EOS Denver.

WHY? **I want to learn from the wisdom contained in this group.** I want to contribute and collaborate with a group focused on driving education and value for the community. I ONLY want to associate with those that have a shared desire to elevate the condition of the humans around them. The people I have interacted with at EOSNation group seem to share that desire. **## And as the DAC grows, if there are additional responsibilities required of me, then I am definitely up to the task.** 

VOTE HUGHES 2018!!
 
Social Media Accounts 
Facebook: https://www.facebook.com/brandon.hughes.581
Steemit: In process
LinkedIn: https://www.linkedin.com/in/brandon-hughes-crpc/
Twitter: https://twitter.com/EOSDenver
Meetup: https://www.meetup.com/EOSDenver/

**Comment by DenisCarriere** [comment]
Thank you @EOSDenver for joining our EOS Nation Ambassador program, thanks for the EOS Nation shoutout on [`Beyond Bitcoin | EOS Talk | Guest: EOS Denver`](https://www.youtube.com/watch?v=u30CvsAvGHg), really appreciate it 😄 

We should discuss how EOS Nation can support EOS Denver (yourself & @stevefloyd) over a video call (Google Hangout/Meet), would there be a particular day or time that works for you?

For private details, you can email us directly at info@eosnation.io or find one of our Admins on our public Telegram chat https://t.me/EOSNation

**Comment by EOSDenver** [comment]
Denis, 

I am definitely looking forward to it. After the EOSRISE event that I’m currently flying to now in San Francisco, I’m immediately going out of the country. I need to put a reminder on my calendar to connect with you after this week.

Let’s connect after 3/20/2018.

Looking forward to talking with you soon,

Brandon Hughes
EOSDenver

**Comment by DenisCarriere** [comment]
👍 Thanks for the reply Brandon, let's keep in touch.

We will also add a calendar reminder to get in touch with you after March 20th.

Best of luck with EOSRISE, looks like an awesome event.

**Comment by DenisCarriere** [comment]
@EOSDenver Great to hear, I hope you're EOS Rise event was successful, we should definitely grab a video call this week?

We can sync up over Telegram for an exact time/day.

**Comment by EOSDenver** [comment]
Denis,

I have time at 9am MST Thursday or 11:30am MST tomorrow. Will either of those work?

**Comment by DenisCarriere** [comment]
@EOSDenver I think 11:30am MST would work for most of us, what's your email so we can send you a Google Calendar invite with the video conference link.

**Comment by EOSDenver** [comment]
Excellent. It might actually be around 11:35 AM because I have appointments right before but that will work. I have not coordinated with Steve Floyd so this time it will be just me. Let me know steps to dial out to you.

**Comment by DenisCarriere** [comment]
@EOSDenver Ok, here's the Google Meet link for the video conference call.

https://meet.google.com/emb-wxez-fyz
